### ISSUE TITLE
Not working as it should

### ISSUE THREAD

**Issue by matej118111** [KeenRivals/bestmotherfucking.website#59] opened 2022-01-04 16:55 UTC
There's no fuck-yo-mother feature

**Comment by jtagcat** [comment] 2022-01-04 17:59
Duplicate of #58

_open yo eyes!!_

**Comment by matej118111** [comment] 2022-01-04 20:31
damn

**Comment by KeenRivals** [comment] 2022-01-05 13:19
Should be good now. Reopen if you continue to see problems.

**Closed as completed by KeenRivals** 2022-01-05 13:19 UTC
